---
title: How I rose from the dead in my spare time and so can you
subtitle: ANZJS Quarto Template
format:
  quarto-anzjs-pdf:
    keep-tex: true  
    shorttitle: How I rose from the dead
    double-space: true
    line-numbers: true
    # You can specify extra preamble in the file below.
    include-in-header:
      - template-header.tex
date: today
date-format: "YYYY" # used to define volumeyear
author:
  - name: A. J. Specktowsky
    affiliations:
      - name: School of Hard Knocks
        department: Department of Redundancy Department
        address: Great Falls, MT 54321, USA
    orcid: 0000-0000-0000-0000
    email: sm@example.org
  - name: Philip K. Dick
    affiliations:
      - name: School of Design Terrace
        department: Complaints Division 
        address: 30102 East Rhode Island, Small Planet, Near Betelgeuse
  - name: Rolf Turner
    affiliations:
      - name: University of Auckland
        department: Department of Statistics
        address: Private Bag 92019, Auckland 1142, New Zealand
    email: r.turner@auckland.ac.nz
  - name: Emi Tanaka
    corresponding: true
    email: emi.tanaka@anu.edu.au
    affiliations: 
      - name: The Australian National University
        department: Biological Data Science Institute
        address: 46 Sullivan's Creek Road, ACT 2600, Australia
# Note that the Journal requires that a paper must begin with a
# "Summary" not an "Abstract".  This is automatically taken care
# of by the anzsauth document style.  So even though the following
# says "abstract" the heading "Summary" will appear in
# the processed version.
abstract: |
  This document serves to illustrate some of the main features of
  the Quarto based on \LaTeX{} document class `anzsauth` which authors are
  strongly encouraged to use when preparing papers for submission
  to the _Australian and New Zealand Journal of Statistics_.
  The importance of clarity of exposition as well as a number of
  issues that frequently arise in respect of the Journal's standards
  and conventions are emphasised.  The Journal has precise requirements
  for the format of bibliographic references and citations.  It is much
  easier for authors to conform to these requirements if they use the
  resources provided by \BibTeX{} and the `anzsj` bibliography
  style (used as default in this template).  Authors are very strongly encouraged to avail themselves
  of these resources.  The use of \BibTeX{} syntax is illustrated.
  This document emphasises a few of the notational conventions that
  form an important part of the Journal's stylistic requirements.
  A great deal more material about these requirements may be found
  in the document "_ANZJS Style Guide for Authors_" in the
  file [`styleGuide.pdf`](https://github.com/emitanaka/quarto-anzjs/blob/master/styleGuide.pdf).
# Below shows how acknowledgements should appear in the Journal.
# Note that if you are acknowledging financial support, grant
# numbers should *not* usually be specified.
acknowledgement: >
  The author acknowledges that this template is based on the latex template for Australian and New Zealand Journal of Statistics and intersperses some text from the original prototype document. \newline\vspace{1ex}\newline
  Opinions and attitudes expressed in this document,
  which are not explicitly designated as Journal policy, are those of
  the author and are _not_ necessarily endorsed by the Journal,
  its editorial board, its publisher Wiley or by the Australian
  Statistical Publishing Association Inc.
# Note that "keywords" should not include words and phrases
# that form part of the title of the paper.
# Also keywords (with the exception of proper names and
# certain abbreviations that conventionally appear all in
# capital letters) should *not* be capitalised.
keywords: [anzsauth, bibliographic references, bibtex, citations, document class, notational conventions, style guide]
bibliography: bibliography.bib  
#nocite: |
# @PussyRiot2014, @Nixon1984, @Turner2017, @Brillinger2007
---

# Introduction {#sec-intro}

This document show how to use the `anzjs` Quarto document so as
to be able to produce an article conforming to the Journal's
requirements with a minimum of effort.  The correponding template can be found at 

<https://github.com/emitanaka/quarto-anzjs>


You are advised to _look carefully_ at the source file
`template.qmd`, and to spend a little while studying the
examples.  In particular, read the _comments_.



Papers submitted to the Journal should be
_double spaced_ and should have their lines _numbered_.
This is important in as much as it makes it easier for referees and
technical editors to indicate where corrections are required.  Double
spacing and line numbers are included by default, but you can disable these by setting `double-space` and `line-numbers` to `false` in the `format` field of the front matter.

A primary requirement that the Journal imposes is that papers must
be written lucidly and in clear and grammatically correct English.
Consequently @sec-clarExpos is devoted to issues that
arise in respect of good exposition.  Other requirements include
proper formatting of the title page.  This is done _far_
more easily if you make use of the resources provided by the
`anzsauth` document class than if you attempt to do the
formatting "by hand".  (See @sec-titPage).

The Journal insists that citations should be formed correctly and in
accordance with its conventions.  Likewise the list of references
must have the correct structure.  Again these requirements are
_greatly_ facilitated if you make use of the resources provided
(by means of \BibTeX\ and the `anzsj` bibliography style).
These matters are discussed in @sec-bibRef.

Although this is _not_ handled in an automatic manner,
it is important to adhere to the Journal's notation conventions.
Most of the discussion of notational conventions has been placed in
"_ANZJS_ Style Guide for Authors" to be found in the
file [`styleGuide.pdf`](https://github.com/emitanaka/quarto-anzjs/blob/master/styleGuide.pdf).

Some of the more salient points about notation are dealt with
in @sec-noteConv in the current document (thus
overlapping a bit with the style guide).  Displayed equations
and their numbering are dealt with in @sec-eqnNumb.
In this section some cogent advice is given about handling arrays of
equations.  Issues that arise in respect of the inclusion of figures
and tables in a paper are discussed in @sec-figAndTab.
In @sec-crossref some remarks are made, and avuncular
advice given, about cross referencing.  @sec-append
presents the Journal's policy about how appendices should be headed.
It also describes the `Appendix` and `uniqueAppendix`
environments that are now provided by the `anzsauth` document
class and that make it easy for you to make sure that your appendices
are headed in the correct manner.  @sec-prepDocs
provides a little bit of advice about preparing and processing the
"source files" that underlie the use of \LaTeX.

It has been pointed out to me that some authors need some
guidance as to what to do with the files `anzsauth.cls` and
`anzsj.bst` which come as part of this template. 

Various exhortations are reiterated, and some advice about
how to make use of `template.qmd` is given in
@sec-concComm.  In this last Section you are
additionally exhorted to create a _tidy_ Quarto source file.

# Clarity of exposition {#sec-clarExpos}

Obviously the fundamental consideration in respect of assessing a
paper's quality is its actual content: its correctness and its value
in terms of the advancement of statistical science.  Second only to
content is the quality of the exposition of the ideas developed in
the paper.  There is little merit in having high quality content
if the paper is written in such a manner that its audience finds
it burdensome or even impossible to read.

The Journal has very exacting standards for the quality of English
expression in the papers it publishes.  Authors are expected to
think carefully about the way in which they present material.
Ideas should flow in a logical manner.  The connections between
successive segments of the material should be obvious and easy to
follow.  Succinct and well-organised examples, kept as uncomplicated
as possible, should be provided to clarify intricate concepts.
It is _not_ acceptable to throw down a jumble of ideas in random
order and expect the reader to sort them out.  Sufficient explanation
should be provided so that any reasonably well-educated statistician
who is willing to expend a reasonable amount of effort will be able
to understand the paper.  It is _not_ acceptable for the paper
to be comprehensible only to experts in the relevant field of study
(or, worse, only to the authors!).

Diligent attention must be paid to grammar.  For instance
_articles_, definite ("the") and indefinite ("a" or
"an") must be used appropriately.   It is not acceptable to omit
articles where they are required, to insert an article where none
is required, or to use a definite article where an indefinite one is
required or vice versa.  In a similar vein, agreement in "number"
between subject and verb must be carefully maintained.  Authors must
guard vigilantly against the use of dangling or misplaced modifiers
(an unfortunately common type of error).

A typical example of a dangling modifier is "The SE of the
correlation increased in size when changing from 4 to 5 quadrature
points.  This sounds as if the SE changed from 4 to 5 quadrature
points!  A grammatically correct phrasing might be something like
"The SE of the correlation increased in size when the number of
quadrature points was changed from 4 to 5."  A typical example of a
misplaced modifier is "A plot of the residuals from Specktowsky's
model shown in Figure 42 indicates the lack of an adequate fit."
(The _model_ is not shown in Figure 42!)  Better would be
"A plot, shown in Figure 42, of the residuals from Specktowsky's
model indicates the lack of an adequate fit."

Some might argue that grammatical issues like these "don't
really matter" and that "the meaning is clear".  The meaning
is _sometimes_ clear, and sometimes becomes  possible to
discern only after readers have expended considerable effort that
has been unnecessarily imposed upon them.  Grammatical errors are
distracting and confusing.  Reading a paper containing grammatical
errors is an unpleasant experience, and readers will be discouraged
from giving a paper containing such errors the attention that it may
otherwise well deserve.  Such errors are an unnecessary encumbrance
to a paper and can be avoided with a modicum of care and diligence.
The Journal insists that such diligence be exercised.

In addition to being written with logical clarity and being free
of grammatical errors, manuscripts should be concise and expressed
in a direct style. Sentences should be kept short; long sentences
are hard to follow and should always be judiciously broken into
a number of shorter sentences.  Distracting use of unnecessary
technical terms should be avoided.  Do not abbreviate terms
unless they are used repeatedly and the abbreviation is helpful
to the reader. Initially use the word in full, and follow it by
the abbreviation in parentheses.  Thereafter use the abbreviation
only. Do not abbreviate author names; for example "Hall and Heyde
(HH)" must _not_ be used.

Care must be taken with the tense of verbs.  Use the past tense
when describing something that was done in the past! In particular
simulations should be described in the past tense.  For example say
"We generated 1000 data sets from our parametric model \ldots"
and not "We generate 1000 data sets \ldots".  Use the past tense
when referring to results from existing literature.  For example,
use "Smith \& Jones (2007) showed that two plus two equals four",
not "Smith \& Jones (2007) show that two plus two equals four".
Use the present tense in referring to the content of the paper that
you are writing: "In this paper we show that the convergence rate
is $o_P(n^{-2/3})$."  (Not "we showed that".)

It is the responsibility of the authors to ensure that the use
of English language in the manuscript is of a quality suitable
for the Journal. If you are not absolutely confident that this
requirement is fully satisfied, then have your manuscript checked
and _thoroughly_ edited by a suitably qualified person.
Such a person (whose first language should preferably be English)
must have superior English language skills and also be qualified
in statistics so as to be able to assess and correct the expression
of statistical ideas.

Failure to ensure an adequate standard of English expression may
result in the paper's being rejected at the Technical Editing stage
_even though_ it has previously been assessed by referees
and and an associate editor as being acceptable for the Journal.
Referees are experts in the particular field addressed by a given
paper and they assess that paper for correctness and value of
statistical and scientific content. They rarely read the paper
carefully in respect of style and exposition, assuming that this is
not their responsibility.  This is why the Journal explicitly leaves
final acceptance to the Technical Editor.  The Journal also reserves
the right to modify an accepted paper so as to reduce inadequacies of
exposition.  Any such modifications will be discussed with authors,
where feasible.

The Journal's publisher, Wiley, provides a service that can assist
authors with English-language editing.  To find out about this
service you may visit:

<http://authorservices.wiley.com/bauthor/english_language.asp>

Authors must be aware that there is a _cost_ associated with
this service, and this cost must be borne by the author(s) of the
paper in question.

# Formatting the title page {#sec-titPage}

Do not try to create the list of authors, their affiliations
and their addresses by hand.  This is difficult, kludgy and
usually leads to results that are not in keeping with the
Journal's requirements (which eventually makes more work for
the typesetters).  Look into
the _source_ file (`template.qmd`) that was used to
produce this document. By looking at the structure of this source file,
you should be able to quickly discern the way in which the frontmatter 
should be used.


Note also that when specifying the abstract, the template 
produces the correct heading "**Summary**" as required by
the Journal.

By learning to use these resources you will in the long
run save a _great_ deal of time and dramatically reduce the
effort that you expend.

## Bibliographic references {#sec-bibRef}

## The Journal's citation rules {#sec-citeRules}

The Journal (for the sake of consistency; see
@sec-noteConv) imposes a number of strict rules
or conventions on the way that citations are formed.  Authors
_must_ follow these conventions.  Just as you are advised not
to format the title page "by hand", you are strongly encouraged not
to produce your citations and your list of references in an ad hoc
one-by-one manner.  Instead use the (very well designed) tools that
are available for the purpose.  That is, make use of \BibTeX\ and
the `anzsj` bibliography style (see @sec-useBib).
If you do so, then (most of) the Journal's required conventions will
be followed automatically, thereby saving you a great deal of work
and a great many headaches.

If you insist on "doing things your own way",
then you must _read carefully_ the relevant section of
"_ANZJS Style Guide for Authors_" and carefully follow the specifications given.

A rule that \BibTeX\ and the `anzsj` bibliography style will
_not_ automatically handle for you is that the names of journals
appearing in the reference list must _not be_ abbreviated.
This is a
\begin{center}
{\large \textbf{CHANGE or REVERSAL}}
\end{center}
of Journal policy from what it has been in the past. (One might
be inclined to say that it is an "about face" or retreat, or
climb-down.)  If you have struggled to dutifully make your references
accord with the previous policy that demanded that journal names
be abbreviated in accordance with "standard abbreviations" and
have arduously combed the web to find out just what these standard
abbreviations are \ldots\ well, I can only apologise.  You are however
owed some explanation:

The Editorial Board were unanimously of the opinion that
the policy of demanding abbreviated Journal names was probably
adopted in the dim distant past to save time for typesetters,
and has little function in today's circumstance.  The only actual
benefit of this policy is that there is a tiny space saving,
and this tiny benefit comes at the cost of unnecessarily adding
tedious work to authors' responsibilities.  It also has the
disadvantage of making our papers less accessible to readers,
especially non-statisticians/mathematicians. Some readers may know
that _Stat. Neerl._ is _Statistica Neerlandica_,
but many will not.  The change in policy is one small step toward
making statistics research more user-friendly.

Consequently _please_ do not abbreviate journal names.  At all.
Ever.  Please _consistently_ give journals their full title.
Again I apologise (on behalf of the Editorial Board) if this causes
you inconvenience and results in your having wasted (substantial)
time and effort.

Another rule that cannot be automatically handled is that reference
may not be made to a paper "submitted for publication" or to a
"personal communication". The essential criterion for inclusion
in the reference list is that any such reference must be obtainable
by a reader: thus a Technical Report is OK and a paper accepted for
publication is OK.  You may, if you wish, put into the text a kind
of acknowledgement of the form "It was pointed out to me by Fred
Nurk (_pers. comm._) that Bayesian statistics is a load
of dingoes' kidneys."  However such references must _not_
be listed in your bibliography.

Likewise references to unpublished data may be cited in the text
(e.g. "I. Poobah, unpublished data, 2000)" but must not appear in
the list of references.  Otherwise all citations mentioned in the
text, tables or figures must be listed in the reference list. A
work must _not_ appear in the reference list _unless_
it is cited in the text.

# Using \BibTeX\ {#sec-useBib}

Authors are **_STRONGLY_** encouraged to make use of
the resources provided by \BibTeX\ in preparing their lists of references
and in citing these references in their documents.  This is easy
to do and helps to make sure that the reference list and citation
conventions conform to the Journal's requirements.  The Journal
has its own "bibliographic style" ("`anzsj`") which is
based upon the `natbib` package.

To use \BibTeX\ you need to do the following:

1. Prepare a "bibliographic information" (`*.bib`)
file containing appropriately structured information about all of
the references that you will cite in your document.  Note that this
file can contain information about references that you _do not
cite_ in your document.  Only those references cited will appear
in the list of references.  This allows you to prepare a single
bibliographic information file that can be used for multiple papers
with overlapping but not identical reference lists.  Of course
when submitting a paper you may wish to upload only a cut-down
`*.bib` file that contains only the relevant references
(rather than a very large bibliographic information file with a
plethora of irrelevant entries). \newline
The way that the information in your bibliographic information
file should be structured is illustrated by the example file
`bibliography.bib` that accompanies the document that you
are currently reading.  Imitating the entries in this example
file should allow you to create just about any references
you need to use.  Note that some rather off-beat entries in
`bibliography.bib` are not cited in this paper and hence
do not appear in the bibliography.  This is in accordance with
the rule that _only_ literature which is actually cited
may appear in the list of references.  Four of these entries are
referred to in commented-out `nocite` in the front matter at the start
of the source file `template.qmd`.  If you want to see what
bibliography entries these items would produce, just un-comment the
`nocite` lines and then compile `template.qmd`.
More information about the structure of `*.bib` files may
be found in @MittelbachGoossens2004.  There are also many
resources to be found on the web by doing a Google\texttrademark\
search on "`bibtex`".

At the start of your Quarto document, add `bibliography: xxx.bib` where "`xxx.bib`" refers to the name of your bibliographic information file.


## Citing references {#sec-citRef}

Cite references by using `@ref-id` and variants
thereof.  Some discussion of the possible variants is to be
found in @sec-citeVar.  The `ref-id`` represents the identifier for the item
being cited.  If you (sensibly) use \BibTeX, the identifier
is provided in the first line of the bibliographic information
about the item being cited.  For example _The_ \LaTeX\
_Companion_ referred to above was cited in this document
via `@MittelbachGoossens2004`.  The relevant item in
`bibliography.bib` begins

```
    @book{MittelbachGoossens2004,
```

If you do not use \BibTeX, then the identifier
is given as the "`cite_key`" for the appropriate item
in the list of references following `\begin{thebibliography}{...}`
line in your \LaTeX\ document.

The way that the identifier is formed is fairly arbitrary; construct
identifiers in your bibliographic information file in whatever way
suits your fancy.  My personal paradigm is to construct identifiers
from the author's name (or authors' names) followed by the year as
in the example given above.  If there are more than two authors I
just use the first author's name followed by "EtAl" and the year.
E.g. for an article by Fred Nurk, Melvin Mingdinkler and Hoo Hee,
published in 1984, I use the identifier `NurkEtAl1984`.
I emphasise that this is just my personal convention that I have
found useful; you are under no obligation to follow it.

## Variants of the basic citation command {#sec-citeVar}

In addition to the "usual" citation command "`@ref-id`"
there are a number of alternative citation commands that can be used
to create special punctuation structures in particular circumstances. See more on the Quarto documentation site [here](https://quarto.org/docs/authoring/citations.html#sec-citations).

Yet another variant of `@ref-id` is `[@ref-id]` which
encloses the whole citation, rather than just the year, in
parentheses.  E.g. "Some authors prefer the hack [@Cook1966],
others the hew [@Moore1967], and still others opt for a
combination [@CookMoore1968]."



## Notational conventions {#sec-noteConv}

It may seem dogmatic, but the Journal has some strict rules
about notational conventions that must be followed.  The reason
for these rules is simply _consistency_.  One and only one
convention must be followed, otherwise the result is a visually
unpleasant hodge-podge.  Which convention is chosen does not
usually matter very much, but a single one must be chosen and
used consistently.  The choice is made by the Journal; authors
must follow it.

A few of the more important examples of these conventions are
listed below.  Many others are given in the document "_ANZJS_
Style Guide for Authors" as mentioned in @sec-intro.

1. The transpose operator:  This must be represented as a
sans-serif $\top$, which is most easily rendered in \LaTeX\
by `\top`.
1. The symbols "$\forall$" and $\exists$: Do _not_
use them!  Use _words_ --- "for each" or "for all" and
"there exist(s)".
1. Random and non-random quantities:  (Scalar) random variables
should generally be denoted by upper case letters such as $X$ or $Y$.
Non-random quantities should be denoted by lower case letters. An
observed value of $Y$ would be denoted by $y$.
1.  Vectors and matrices:  Vectors quantities should be indicated
by bold face font, e.g. $\by$.  Vectors of observations should
be presented as (boldface) lower case letters (such as the $\by$
example just given) whereas vectors of random variables should be
presented as bold face upper case letters: $\bY$.  Matrices should
also be presented as bold face upper case letters: $\bM$.  To help
you to adhere to these conventions there are now commands `\bx`,
`\by`, `\bX`, `\bY`  and `\bM` defined in the
`anzsauth` document class that produce $\bx$, $\by$, $\bX$,
$\bY$ and $\bM$ respectively.  To get other bold face letters,
have a look at the file `anzsauth.cls` and imitate the
construction of the foregoing commands.
1. Expectation:  Use "E" (upright Roman font) for the
expectation operator, and enclose the argument of this operator in
_parentheses_ as in $\E(X)$. \label{op:expect}
1. Variance, covariance and correlation:  Likewise use "var",
"cov" and "cor" (ordinary Roman font, all lower case) for the
variance, covariance and correlation operators, as in $\var(X)$,
$\cov(X,Y)$ and $\cor(X,Y)$. \label{op:var}
1. Probability: Use "$\Pr$" for the probability function,
and enclose the argument of this function in _parentheses_
as in $\Pr(A)$.  The probability function is best rendered
in \LaTeX\ by using `\Pr`.
1. Do not begin sentences with symbols (mathematical or
otherwise).  A sentence _must_ begin with a _word_
that can be capitalised. For example, instead of "$\Phi(x)$ is
a cumulative distribution function \ldots", use "The function
$\Phi(x)$ is a cumulative distribution function \ldots".


To help you adhere (effortlessly!) to the conventions specified
in items \ref{op:expect} and \ref{op:var} there are now commands
`\E`, `\var`, `\cov` and `\cor` defined in the
`anzsauth` document class.  This is effected by means of the
`\newcommand{}` facility provided by \LaTeX.  These commands
produce the required form of the expectation operator and the
variance, covariance and correlation operators.

Other notational structures can be created in a similar manner.
Look into the `anzsauth.cls` document class file; it's a plain
text file; it won't bite!  By imitating `\E`, `\var`,
`\cov`, `\cor` and other examples, you will be able to
construct a convenient "shorthand" that will allow you to produce
notation conforming to the Journal's requirements using a minimal
number of keystrokes.

## Equation numbering {#sec-eqnNumb}

An equation should be given a number **_ONLY IF_**
if it is referred to elsewhere in the paper.
Use `$$ ... $$` to display an equation _without_ a number.
You can use `\begin{align*} ... \end{align*}` for equations that span mulitple lines.
You will need to have the package `amsmath` loaded in order
to have access to the `align*` (and the `align`
and `split` --- see below) environments.  Examples:

$$\Pr(K = k) = \binom{n}{k} p^k (1-p)^{n-k}$$

and
\begin{align*}
P_0(x) &= 1 \\
P_1(x) &= x \\
P_2(x) &= (3x^2 - 1)/2 \\
P_3(x) &= (5x^3 - 3x)/2 \\
       & \ldots \\
P_{n+1}(x) &= ((2n+1)xP_n(x) - nP_{n-1}(x))/(n+1)
\end{align*}
Use `$$ ... $$` followed by an equation id, e.g. `{#eq-example}` to display an
equation _with_ a number.  You can use
`\begin{eqnarray} ... \end{eqnarray}` to display an array of
equations with numbers, but as for un-numbered arrays of equations it
is better to use `\begin{align} ... \end{align}`.  Very often
you will wish to have only one number associated with an array of
equations.  To suppress equation numbers you can use the
`\nonumber` command with `align`, but you get a sexier
result if you use `split` inside an equation environment.
Examples:
$$
\E \left (\sum_i h(x_i,\bX \setminus \{x_i\}) \right )
= \E \left ( \int_W h(u,\bX) \lambda(u,\bX) \; du \right )
$$ {#eq-GNZ}
and

$$\begin{split}
\alpha \beta &= \bar{x} \\
\alpha \beta^2 &= s^2 \;\; .
\end{split}
$$ {#eq-gammaMM}

Note how the label (i.e. "([-@eq-gammaMM])") is vertically
centred with respect to the array of equations.  See the \LaTeX\
source for the foregoing example in the file `template.qmd`
for guidance as to how all this is done.

Displayed equations which _are_ numbered should be numbered
consecutively (1), (2), \ldots, throughout the paper, including
in the appendices if any.  (I.e. they should _not_ be numbered
"within sections".)  The required behaviour is the default in
\LaTeX.  As long as you do not take any overt action to mess it up,
you will get the appropriate style in your document.

## Figures and tables {#sec-figAndTab}


Figures and tables often cause problems with the processing
of papers.  Here are a few comments on the preparation and
presentation of such displays, with an example of each type.
Of course the "content" of these examples is just flippant,
frivolous nonsense, as my examples usually are.  (These examples
are meant to be humorous; as I indicated previously, whether you
find them funny depends on your sense of humour.)

It can be a major annoyance if authors supply each panel of a
multi-panel figure as a separate figure file.  When this is done,
authors usually proceed by arranging the panels, within an array
that constitutes a single figure, by juxtaposing the commands used
to input the figures in an appropriate manner and interleaving
appropriate line breaks.  Although this is all do-able, and may
lead eventually to a visually acceptable figure, it makes extra
work both for the author and for the typesetters.  It may also add a
substantial amount of tedious work to the procedure of uploading
the final version of the paper to ScholarOne if you upload the
figures individually (rather than in a zip archive, this last
now being acceptable to ScholarOne).

It is much better to create a multi-panel figure in a single figure
file, using appropriate graphics techniques.  

![Characteristics of the Lesser Tasmanian Drop Bear (farkling
fraction, intracranial perspicacity and serendipity all in
furlongs per fortnight) plotted against body mass (kilograms).
The observations were made on samples obtained at four locations
in Tasmania. Plotted points represent the raw observed values;
plotted lines represent non-parametric fits to the raw data.](ltdbFigure){#fig-ltdb}


Another important issue is making sure that line types and
plotting symbols are _distinguishable_ in black and white.
Figures appear in the print version of the Journal in black and
white _only_, unless authors specifically request that some or
all of the figures appear in colour and are _willing to pay
a charge_ to cover the extra costs that are incurred in printing
colour figures.  So unless you wish to pay this charge --- roughly
speaking \$350 USD per figure --- you should prepare your figures
in black and white, and do this from the very start. (Figures
that are prepared in colour and then converted to black and white
in the printing process usually look awful! Consequently the Journal
does not countenance this practice.)  In particular, lines in
different categories should be distinguished by _line type_
--- solid, dashed, dotted \ldots, and not by colour.  A modest
example is given in @fig-ltdb.  Sometimes it is useful,
or perhaps even necessary, to distinguish categories by means of
line _thickness_ but proceeding in this way requires a great
deal of care.

Note that colour figures can appear in the online version of the
paper for _free_!  However care must be taken, since _only
one_ version of the text of the paper is produced.  Consequently
the online colour figures, and captions and references to figures
in the text, must be structured in such a way as to make sense
both to readers of the black-and-white (print) version and the
colour (online) version.  See `styleGuide.pdf`, Section
5.1, for a bit more detail.

A common error in respect of tables is making them overly elaborate.
Remember that the purpose of a table is to convey information! If
a table is excessively complex, the reader's eyes will glaze over
and he or she will skip the table, resulting in no information at
all being conveyed.  In particular, if a table is too wide to fit
on a page and has to be rotated 90$^\circ$ in order to be displayed,
then you are trying to put an excessive amount of information into
a single table.  The Journal will henceforth _insist_ that
tables fit vertically onto a single page.  If your paper contains
tables that do not satisfy this condition then you will be required
to re-design your table accordingly.  Possibilities for effecting the
re-design include eliminating some of the "information", splitting
the table into two or more smaller tables and putting all or part
of the table into the online supplementary material.  An example
of a reasonably perspicuous table is given in @tbl-ltdb.

Location | Body mass (kg.) | Farkling fraction | Intracranial perspicacity | Serendipity 
-----------|------------:|---------------:|---------------:|------------:
Port Arthur |  3.95 ( 2.40) | 10.14 ( 2.43) |  9.91 ( 1.99) |  9.81 ( 2.24) 
Melaleuca   |  4.55 ( 2.41) | 10.48 ( 3.51) | 10.83 ( 2.94) | 10.54 ( 3.30) 
Wynyard     |  3.87 ( 2.70) |  9.51 ( 2.20) |  9.40 ( 2.44) |  9.50 ( 2.23)  
Bicheno     |  4.16 ( 2.41) | 10.46 ( 2.44) | 10.44 ( 2.64) | 10.20 ( 2.86)  

: A load of dingoes' kidneys in respect of characteristics of the Lesser Tasmanian Drop Bear.  Standard deviations are given in parentheses after the mean values. {#tbl-ltdb}


As stated in the "_ANZJS_ Style Guide for Authors"
captions for tables and figures should be left-justified and not
centred unless the text of the caption fits on a single line.
However one-line captions should be centred.  For instance if the
caption of @tbl-ltdb were simply "Dingoes' kidneys",
then centring would be preferable.  When the `anzsauth`
document class is used, captions are automatically centred if
the caption fits on a single line.  (Note that the document
class file `anzsauth.cls` has recently --- as of
\printdateTeX{2016/11/06} --- been adjusted to make table captions
more similar in appearance to figure captions.  Because of this
adjustment, the centring of one-line table captions is now automatic
whereas, previously, overt measures were required.)

A table or figure that appears in the paper _must_ be referred
to in the text, even if only very briefly.  That is, there must
at the very least be something like "see Figure~17".  If there
is no such reference, then the corresponding table or figure must
not be included in the paper.

# Cross referencing {#sec-crossref}

A facility provided by \LaTeX\ that tends to be underused in
submissions to the Journal is automated cross-referencing as provided
by the `@...` and `#` commands. See Quarto documentation for more on this! It is
highly recommended that you learn to make use of these.  They make it
much easier to keep cross-references correct when you revise a paper.
It seems to me to be a good idea to give a label to each section and
subsection, as you are composing it, even if you are not sure you
will be referring to it in other sections.  (There is no _harm_
in inserting a label.)  If you assign labels to sections then you
can easily invite the reader to "see @sec-figAndTab"
(as I am about to do below!).  Likewise it is a good idea to give
each figure and table (see @sec-figAndTab) a label so
as to be able to refer to it via the `\ref{...}`  command.

Only displayed equations that are _actually referred to_
should be numbered (see @sec-eqnNumb).  If the equation
_is_ referred to, then of course you should give it a label so
that you _can_ refer to it easily.

My personal practice is to label sections and subsections with labels
of the form `sec-string`, e.g. "`#sec-intro`".
Similarly I form such labels for figures and tables
as `fig-string` or `tbl-string` (e.g.
`@fig-ltdb` or `@tbl-ltdb`) and labels
for equations as `@eq-string` (e.g. `#eq-GNZ`).
I find this practice convenient, but you are of course under no
obligation to follow it.

A practice that I have often seen and that I think should _not_
be indulged in, is to use labels such as "`Figure1`".  There
is _not necessarily_ any harm in this, but to a large extent
such a practice defeats the purpose of using dynamic labels.  If you decide to change the order in which
figures appear in your paper, then the label "`Figure1`"
will probably no longer be appropriate.  At best you will confuse
yourself, and you run a serious risk of getting labels wrong.
Use labels that refer to _content_ (in a terse manner, of
course) and let \LaTeX\ handle the assignment of numbers!  If you
insist on using labels like unto "`Figure1`",
then take great care to make sure that the result is correct.

# Appendices {#sec-append}

Journal policy is that if there is a single appendix to your document
it should be headed simply '**Appendix**' (i.e. there should
be no other text in the header and no number).  If the document
has more than one appendix these should be headed **Appendix**
I, **Appendix II**, \ldots (i.e. there should be no
other text in the headers, and numbering should be in upper case
Roman numerals).  

Do _not_ use the 'native' \LaTeX\ command `\appendix`!.

To make it easy to supply appendix headers in the appropriate style,
the `anzsauth` document class provides two new environments:
`uniqueAppendix` and `Appendix`.  Use the former
if your document has a single appendix, and the latter if it has
more than one.  The use of the `Appendix` environment is
illustrated by means of the dummy appendices Appendix~\ref{app:mung},
Appendix~\ref{app:gorp} and Appendix~\ref{app:zephod}.  These mostly
consist of "Lorem ipsum" nonsense Latin and are to be found at
the end of this document that you are currently reading.

The `\label{}` and `\ref{}` commands work with appendices
(when there are multiple appendices).  Just put a label within
the relevant `Appendix` environment and then refer to that
appendix with constructions like "`See Appendix~\ref{lll}`",
where "`lll`" is the label that you have assigned to the
Appendix in question.  Obviously if you have a unique appendix
you can just say (e.g.) "See the Appendix \ldots" and there
is no need for labelling.

In order to illustrate the use of `uniqueAppendix` I had to
invoke it even though there are actually multiple appendices (four
in all) in this document.  Don't _you_ do that!  Do as I say,
not as I do!

The text constituting the illustration of `uniqueAppendix`
consists of a recapitulation of the foregoing note.

# Preparing \LaTeX\ and \BibTeX\ documents {#sec-prepDocs}

## Editing \LaTeX\ source files {#sec-editors}

There are a number of approaches to preparing your `*.tex`
and `*.bib` files. A primary consideration is that you should
use either a general **text editor**, or a specialised \LaTeX{}
editor for this task.  Do _not_ use a word-processing program as
an editor. Using a word-processor introduces a plethora of spurious
non-printing characters which will completely mess things up and
in all likelihood cause the universe to come to an end.

Good text editors include `vi` or `vim`,
`emacs`, `gedit`, `pico`, `Crimson`,
`Notepad++`,~\ldots\ .  Good editors will have support
for editing of \LaTeX{} such as syntax highlighting and code
completion. The Windows\texttrademark\ editors `Notepad`
and `Wordpad` are distinctly inferior in this respect.

Among a number of possible specialised \LaTeX{} editors, one that
has been highly recommended to me by several reliable sources
is `TeXstudio`. This is an open-source, multi-platform,
fully-featured editor for \LaTeX{}. It allows for easy processing of
documents, has support for inclusion of a vast range of characters,
provides auto-completion of \LaTeX{} commands, has a built-in pdf
viewer and a number of other helpful facilities. Other similar
programs are `Texmaker` and (Windows\texttrademark\ only)
`WinEdt`.

Users of Windows\texttrademark\ will almost surely make use of
\LaTeX\ via \MiKTeX.  This is free open source software, and is
readily available and easy to install.

The integrated development environment (IDE) `proTeXt` is
described as being "an easy-to-install \TeX{} distribution for
Windows\texttrademark, based on `MiKTeX`", "which adds
the `TeXstudio` front end to MiKTeX".  Some authors may
find it helpful.


# Concluding comments {#sec-concComm}

This document contains guidance on how to prepare a paper for
submission to _ANZJS_ by making use of the `anzsauth}
document class for \LaTeX.  You will find that by making use of this
document class and following the advice that is provided in the
foregoing material, you will be able to produce a paper that meets
the Journal's requirements and that requires much less revision and
adjustment than it otherwise might, thus speeding up the publication
process considerably.

This document also emphasises the importance of good exposition and
correct use of the English language.  The Journal has very high,
and strictly enforced, standards in this regard.  Please pay close
attention to this requirement and give careful thought to the way
in which you express yourself.  Doing so will, again, speed up the
publication process for you.

The accompanying file `template.qmd` forms a template for
\LaTeX\ source files for papers that are to be submitted to the
Journal.  When preparing your own \LaTeX\ source file, you should
imitate the structure of the template closely.  You may find that an
effective way to proceed is to edit the template, _mutatis
mutandis_, replacing authors' names, the title of the paper,
the abstract (summary) and the actual content as is appropriate.
_Please_ remove extraneous bits and pieces from the prototype
file when converting it into your own paper.  Don't leave material
that is relevant only to the prototype (e.g. comments advising
you how to format your paper) lying around.  Tidy up!  This makes
processing your paper for publication much easier (and quicker!).
In respect of tidyness I draw your attention to the last paragraph
of this section (keep the typescript in your source file tidy!).

With regard to removing extraneous material, it turns out to be
expedient for me to mention that the disclaimer at the end of the
footnotes on the title page of this document should _not_ be
included when you adapt the prototype source file to your own uses.
That disclaimer applies to _this paper_, i.e. "**How I
rose from the dead in my spare time and so can you**".  The Journal
does _not_ require you to include such a disclaimer in
_your_ paper, nor should you do so.

Although it is not necessary to prepare the initial submission using
the `anzsauth` document class, it is very important that
the final version that you submit (after provisional acceptance of
your paper) should conform to the Journal's requirements.  This is
much more likely to be the case if you use the `anzsauth`
document class.  It is likely to be less work for you if you make
use of this document class and of the template from the outset,
if this is at all possible. Note that it _is_ necessary for
the initial submission to be double spaced and to be line-numbered.
These requirements are greatly facilitated by using the required
document class.  

It is often the case that the Technical Editor will wish to make
some minor (or sometimes major!) adjustments to the \LaTeX\ source
file that you provide, before putting the paper into production.
This saves having to send the paper back to authors, yet one more
time, to get these adjustments made.  The process of making these
adjustments is a _whole lot_ easier if the source file is
constructed in a tidy and comprehensible manner.  Use appropriate
line breaks (keeping lines to a length of, e.g., at most 80
characters) and ensure that there is appropriate _spacing_
between mathematical constructions.  Do not embed \LaTeX\ commands
to produce displayed equations in on-running lines of text.  All of
this will have of course absolutely no impact on the _output_
file produced by compiling the \LaTeX\ source, but it simplifies
the process of modifying and adjusting this source by orders of
magnitude.

\begin{Appendix}
\label{app:mung}

This is an appendix. \lipsum[1]

\end{Appendix}

\begin{Appendix}
\label{app:gorp}

This is another appendix. \lipsum[2]

\end{Appendix}

\begin{Appendix}
\label{app:zephod}
\begin{center}
Zephod Beeblebrox
\end{center}


\emph{This} appendix was written by Zephod Beeblebrox, but he didn't
actually have anything to say. \lipsum[3]

\end{Appendix}


\begin{uniqueAppendix}

This is what you should get if you had only \emph{one} appendix.
Since this document has several appendices (four, actually) the
use of the \texttt{uniqueAppendix} environment is completely
inappropriate here.  It is included for illustrative purposes
only.  I needed to illustrate syntax to be used both for multiple
and unique appendices, but obviously one cannot have a single
document in which there is a unique appendix and in which there are
multiple appendices!  (That would violate the, uh, law of small
numbers. \verb! :-) !)  Consequently I was forced to include an
inappropriate example of the use of \texttt{uniqueAppendix}.

I reiterate:  Use the \texttt{uniqueAppendix} environment if there is
only one appendix to your document.  Use the \texttt{Appendix}
environment if there are two or more appendices to your document.
\end{uniqueAppendix}



